config/routes.rb
Rails.application.routes.draw do

  resources :ads
  resources :articles
  resources :topics
  resources :regions
  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations" }
  root "articles#index"

  post "/articles/:id/add_new_comment", to: "articles#add_new_comment", as: :article_new_comment
  resources :comments, only: :destroy

end

app/models/ad.rb
class Ad < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :topics
  has_and_belongs_to_many :regions
  has_one :page_position

  mount_uploader :image, ImageUploader

  acts_as_commentable

  def has_topic?(topic)
    topic_ids.include? topic.id
  end

  def has_region?(region)
    region_ids.include? region.id
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/page_position.rb
class PagePosition < ActiveRecord::Base
  belongs_to :article
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_and_belongs_to_many :articles
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def is_admin?
    self.role == "admin"
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

	before_action :set_ad, only: [:show, :edit, :update, :destroy]

	def index
		@ads = Ad.all
	end

	def create
		@ad = Ad.new(ad_params)
			if @ad.save
				redirect_to ads_path, notice: "New ad created."
			else
				redirect_to ads_path, notice: @ad.errors.full_messages
			end
	end

	def update
		@ad.update_attributes(ad_params)
		redirect_to ads_path, notice: "Ad updated."
	end
	
	def destroy
		@ad.destroy
		redirect_to ads_path, notice: "Ad has been deleted."
	end
	
	
	private
	
		def set_ad
			@ad = Ad.find(params[:id])
		end
	
		def ad_params
			params.require(:ad).permit(:image_path, :link_path)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	before_filter :create_search_object

	def create_search_object
		@search = Article.search(params[:q])
	end

	protected

		def configure_permitted_parameters

			devise_parameter_sanitizer.for(:sign_up) do |u|
				u.permit(:name, :username, :email, :password, :password_confirmation, :remember_me)
			end
			devise_parameter_sanitizer.for(:sign_in) do |u|
				u.permit(:username, :password, :remember_me, :login)
			end
			devise_parameter_sanitizer.for(:account_update) do |u|
				u.permit(:name, :username, :email, :password, :password_confirmation, :current_password)
			end
		end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:show, :edit, :update, :destroy]

	before_action :load_ads, only: [:index, :show]


	def index
		@articles = Article.all.order(:updated_at).reverse
		@articles = @search.result.order(:updated_at).reverse
	end

	def show
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article, notice: "Article was successfully created."
		else
			render "new", notice: @article.errors.full_messages
		end
	end

	def update
		if @article.update_attributes(article_params)
			redirect_to @article, notice: "Article was successfully changed."
		else
			render "edit", notice: @article.errors.full_messages
		end
	end

	def destroy
		@article.destroy
		redirect_to root_path, notice: "Article has been deleted."
	end



	def load_ads
		@ads = Ad.all
	end


	def add_new_comment
		@article = Article.find(params[:id])
		@comment = Comment.new(comment_params)
		@comment.user = current_user
		@comment.save
		@article.comments << @comment
		redirect_to article_path(@article)
	end



	private

		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:headline, :standfirst, :image, :caption, :content, :author, topic_ids:[], region_ids:[])
		end

		def comment_params
			params.require(:comment).permit(:comment, :title)
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    redirect_to root_path unless current_user.is_admin?
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to article_path(@comment.commentable), notice: "Comment deleted."
  end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  before_action :set_region, only: [:show, :destroy]

  def show
    @articles = Article.all.order(:updated_at).reverse
  end

  def destroy
    @region.destroy
    redirect_to topics_path, notice: "Region deleted."
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to topics_path, notice: "Region created."
    else
      redirect_to topics_path, notice: "Update failed."
    end
  end

  private

    def set_region
      @region = Region.find(params[:id])
    end

    def region_params
      params.require(:region).permit(:name)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	layout "forms"
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	layout "forms"
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_action :set_topic, only: [:show, :destroy]

  def index
  end

  def show
    @articles = Article.all.order(:updated_at).reverse
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path, notice: "Topic created."
    else
      redirect_to topics_path, notice: "Update failed."
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "Topic deleted."
  end

	private

		def set_topic
			@topic = Topic.find(params[:id])
		end

    def topic_params
      params.require(:topic).permit(:name)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def add_line_breaks(text)
    raw text.gsub(/\n/, "<br>"*2)
  end
end

app/views/ads/index.html.erb
<% if user_signed_in? && current_user.role == "admin"%>

	<div class="medium-8 column">
	
		<h2>Current ads:</h2>
	
		<br>
	
		<% @ads.reverse.each do |ad| %>
			<%= image_tag(ad.image_path, size: "310x500", class: "ad-on-management-page") %>
			
		
			<%= form_for(ad) do |f| %>
		
			<br>
			<%= f.label :image_path %><br>
			<%= f.text_field(:image_path, class: "medium-field") %><br>
		
			<%= f.label :link_path %><br>
			<%= f.text_field(:link_path, class: "medium-field") %><br>
		
			<%= f.submit "Update", class: "button radius medium-button" %>
		
			<% end %>
		
			<%= link_to "Remove", ad_path(ad.id), method: :delete, data: { confirm: "Are you sure  	you want to delete this ad?" }, class: "button radius medium-button" %>
			<br>
			<hr>
		
		<% end %>
	
	</div>
	
	<div class ="medium-4 column">
	
	<h2>Create new ad:</h2>
	
	<br>
	<br>
	
		<%= form_for(Ad.new) do |f| %>
		
			<%= f.label :image_path %><br>
			<%= f.text_field :image_path %>
			<br>
			<%= f.label :link_path %><br>
			<%= f.text_field :link_path %>
			<br>
			<%= f.submit "Create new ad", class: "button radius medium-button" %>
	
		<% end %>
	
	</div>

<% end %>

app/views/application/_ads.html.erb
<% 3.times do %>

	<% ad = Ad.all.to_a.sample %>
	<%= link_to (image_tag(ad.image_path, size: "310x500")), ad.link_path %>
	<br>
  <br>

<% end %>

app/views/application/_debugger_box.html.erb
<!-- Code in this file will show at the top of the page, to help in identifying bugs -->

app/views/application/_footer.html.erb
<footer>

  <br>
  <br>
  <hr>
  <p>&copy 2015 Hanbury Street Rag</p>

</footer>

app/views/application/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1><%= link_to "Home", root_path %></h1>
		</li>
		 <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
	</ul>

	<section class="top-bar-section">
		<!-- Right Nav Section -->
		<ul class="right">

			<% Topic.all.each do |topic| %>
				<li><%= link_to topic.name, topic %></li>
			<% end %> 

			<li class="has-dropdown">
				<a href="#">Regions</a>
					<ul class="dropdown">
						<% Region.all.each do |region| %>
							<li><%= link_to region.name, region %></li>
						<% end %>
					</ul>
			</li>

			<li>
			  <div class="large-8 small-9 columns">
			  <%= search_form_for @search do |f| %>
			    <%= f.text_field :headline_or_standfirst_or_caption_or_content_or_author_cont, class: "radius-left expand", placeholder: "Search the paper..." %>
			  </div>
			    <div class="large-4 small-3 columns">
			      <%= f.submit "Search", class: "radius-right button" %>
			    </div>
			  <% end %>
			</li>

			<% if user_signed_in? && current_user.role == "admin" %>
				<li class="has-dropdown">
					<a href="#">Editor Options</a>
					<ul class="dropdown">
						<% if @article && @article.id %>
							<li><%= link_to "Edit Page", edit_article_path(@article) %></li>
						<% end %>
						<li><%= link_to "New Article", new_article_path %></li>
						<li><%= link_to "Topics/Regions", topics_path %></li>
						<li><%= link_to "Ads", ads_path %></li>
					</ul>
				</li>
			<% end %>

			<% if user_signed_in? %>

				<li class="has-dropdown">
						<a href="#"><%= current_user.username %></a>
						<ul class="dropdown">	 	
						 	<li><%= link_to "My Account", edit_user_registration_path %></li>
						 	<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %></li>
						</ul>
				</li>		
			<% else %> 
				<li><%= link_to "Log in", new_user_session_path %></li>
				<li><%= link_to "Sign up", new_user_registration_path %></li>
			<% end %>

		</ul>
	</section>
</nav>

app/views/application/_masthead.html.erb
<h1 class="masthead">Hanbury Street Rag</h1>

app/views/application/_messages.html.erb
<div class="message_box">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/application/_topics_and_regions.html.erb
<% if user_signed_in? && current_user.role == "admin"%>

  <div class="large-6 column narrow-column">
  
    <h2>Topics:</h2>
    <br>
    <br>
    
    <% Topic.all.each do |topic| %>
      <p class="category-title">&nbsp;&nbsp;<%= topic.name.upcase %></p>
      <%= link_to "Remove", topic_path(topic.id), method: :delete, data: {confirm: "Are you   sure  you want to delete this topic? It will be removed from the header bar and all   articles." }, class: "button radius small-button" %>
      <br>
      <hr>
    <% end %>
    
    <%= form_for(Topic.new) do |f| %>
      <%= f.label "Topic name:" %><br>
      <%= f.text_field(:name, class: "small-field") %>
      <%= f.submit "Add topic", data: {confirm: "Are you sure you want to create a new topic? This will appear on the header bar."}, class: "button radius medium-button" %>
    <% end %>
  
  </div>
  
  <div class="large-6 column narrow-column">
  
    <h2>Regions:</h2>
    <br>
    <br>
    
    <% Region.all.each do |region| %>
      <p class="category-title">&nbsp;&nbsp;<%= region.name.upcase %></p>
      <%= link_to "Remove", region_path(region.id), method: :delete, data: {confirm: "Are you  sure you want to delete this region? It will be removed from the regions dropdown menu and all articles." }, class: "button radius small-button" %>
      <br>
      <hr>
    <% end %>
    
    <%= form_for(Region.new) do |f| %>
      <%= f.label "Region name:" %><br>
      <%= f.text_field(:name, class: "small-field") %>
      <%= f.submit "Add region", data: {confirm: "Are you sure you want to create a new   region? This will appear on the regions dropdown menu."}, class: "button radius medium-button" %>
    <% end %>
  
  </div>

<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

			<ul>
			<% @article.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :headline %><br>
		<%= f.text_field :headline %>
	</div>
	<div class="field">
		<%= f.label :standfirst %><br>
		<%= f.text_area :standfirst %>
	</div>
	<div class="field">
	   <%= f.label :image %><br>
	   <%= f.file_field(:image, class: "uploader-button") %>
	</div>
	<div class="field">
		<%= f.label :caption %><br>
		<%= f.text_area :caption %>
	</div>
	<div class="field">
		<%= f.label :content %><br>
		<%= f.text_area(:content, class: "content-area") %>
	</div>
	<div class="field">
		<%= f.label "Author(s)" %><br>
		<%= f.text_field :author %>
	</div>
	<div class="row">
		<div class="medium-6 columns">
			<div class="field">
				<p>Topics:</p>
				<% Topic.all.each do |topic| %>
				<%= check_box_tag "article[topic_ids][]", topic.id, @article.topic_ids.include?(topic.id)	, 	id: "article_#{topic.id}" %> 
					<label for="article_<%= topic.id %>"><%= topic.name %></label><br>
				<% end %>
			</div>
		</div>
	
		<div class="medium-6 columns">
			<div class="field">
				<p>Regions:</p>
				<% Region.all.each do |region| %>
				<%= check_box_tag "article[region_ids][]", region.id, @article.region_ids.include?(region	.	id), id: "article_#{region.id}" %> 
					<label for="article_<%= region.id %>"><%= region.name %></label><br>
				<% end %>
			</div>
		</div>
	</div>
	
	<br>

	<div class="row">
		<div class="actions medium-6 columns">
			<%= f.submit "Publish", class: "button radius" %>
		</div>
	
		<div class="medium-6 columns">
			<% if @article.id != nil %>
				<%= link_to "Remove", article_path, method: :delete, data: { confirm: "Are you sure you want to delete this article?" } , class: "button radius" %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<%= render "masthead" %>

<div class="row">

	<div class="medium-8 columns">
	
		<% if @articles.count == 0 %>
			<h4>No search results found.</h4>
		<% else %>

			<div class="picture">
				<%= image_tag(@articles[0].image.url, size: "450x315") %>
				<h4><%= link_to @articles[0].headline, @articles[0] %></h4>
				<h5><%= @articles[0].standfirst %></h5>
			</div>
		
			<div class="medium-6 columns">
				<% @articles[1..7].each do |article| %>
						<br>
						<h4><%= link_to article.headline, article %></h4>
						<%= image_tag(article.image.thumb.url, class: "thumbnail") %>
						<p><%= article.standfirst %></p>
				<% end %>
			</div>
		
			
			<div class="medium-6 columns">

				<% if @articles.count > 8 %>
					<% @articles[8..14].each do |article| %>
							<br>
							<h4><%= link_to article.headline, article %></h4>
							<%= image_tag(article.image.thumb.url, class: "thumbnail") %>
							<p><%= article.standfirst %></p>
					<% end %>
				<% end %>

			</div>
		<% end %>
	</div>

	<div class="medium-4 columns">
		<%= render "ads" %>
	</div>

</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<div class="row">

	<div class="medium-8 columns">

		<h1><%= @article.headline %></h1>		
		<h5><%= @article.standfirst %></h5>		
		<div class="picture">
			<%= image_tag(@article.image.url, size:"450x315") %>
			<br>
			<br>
			<p class="caption"><%= @article.caption %></p>
		</div>
		<p>by <%= @article.author %></p>

		<% if user_signed_in? %>
		<p class="article-content"><%= add_line_breaks @article.content %></p>
			<br>
	
			<p>
			<% if @article.comments %>
			<b><%= @article.comments.count %> comments:</b>

				<% @article.comments.each do |comment| %>
					<p><b><%= comment.title %></b></p>
					<p class="comment-author"><i>by <%=  (comment.user && comment.user.name) || "Anonymous" %></i></p>
					<p><%= comment.comment %></p>
						<%= link_to("Remove", comment_path(comment.id), method: :delete, class: "button radius small-button") if current_user.is_admin?%>
					<hr>
				<% end %>

				<b><%= current_user.name %> - add a comment to this article:</b>
			<% else %>
				<b>Be the first to comment on this article.</b>
			<% end %>
			</p>
	
			<p>
				<%= form_tag article_new_comment_path(@article) do %>
					<%= hidden_field_tag "id", :id %>
					<%= text_field_tag "comment[title]" %>
					<%= text_area_tag "comment[comment]" %>
					<%= submit_tag "Post Comment", class: "button radius" %>
				<% end %>
			</p>





		<% else %>
		 
		<p class="article-content"><%= add_line_breaks @article.content.slice(0..350) %>...</p>

		<p><b><%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> to see more content.</b></p>

		<% end %>
		
	</div>
	<div class="medium-4 columns">
		<%= render "ads" %>
	</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>Hanbury Street Rag</title>
		
		<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,200,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=UnifrakturMaguntia' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>

	<body>

		<%= render "header" %>
		<%= render "debugger_box" %>

		<div class="row">
			<%= render "messages" %>
			<%= yield %>
		</div>

		<%= render "footer" %>

	</body>
</html>

app/views/layouts/forms.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>Hanbury Street Rag</title>
		
		<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,200,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=UnifrakturMaguntia' rel='stylesheet' type='text/css'>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "vendor/modernizr" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>

	<body>

		<%= render "header" %>
		<%= render "debugger_box" %>
		<%= render "masthead" %>

		<div class="user-form">
			<%= render "messages" %>
			<%= yield %>
		</div>

		<br>
		<br>
		<br>

	</body>
</html>

app/views/regions/show.html.erb
<div class="row">

  <%= render "masthead" %>

  <div class="medium-8 columns">

    <h1><%= @region.name %></h1>

    <% @articles[0..15].each do |article| %>
      <% if article.has_region?(@region) %>
        <%= image_tag(article.image.thumb.url, class: "thumbnail") %>
        <h4><%= link_to article.headline, article %></h4>
        <p><%= article.standfirst %></p>
        <br>
      <% end %>
    <% end %>
  </div>


  <div class="medium-4 columns">
    <%= render "ads" %>
  </div>

</div>

app/views/topics/index.html.erb
<%= render "topics_and_regions" %>

app/views/topics/show.html.erb
<div class="row">

  <%= render "masthead" %>

  <div class="medium-8 columns">

    <h1><%= @topic.name %></h1>

    <% @articles[0..15].each do |article| %>
      <% if article.has_topic?(@topic) %>
        <%= image_tag(article.image.thumb.url, class: "thumbnail") %>
        <h4><%= link_to article.headline, article %></h4>
        <p><%= article.standfirst %></p>
        <br>
      <% end %>
    <% end %>
    
  </div>

  <div class="medium-4 columns">
    <%= render "ads" %>
  </div>

</div>